name: easydiagno
description: A new Flutter project.

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Versioning
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  flutter_form_builder: ^10.2.0
  http: ^1.6.0
  csc_picker_plus: ^0.0.3
  flutter_svg: ^2.0.9
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/loading.png
    - assets/images/bg.jpg
    - assets/images/loading1.gif

  # Fonts can be added here if needed
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
